# Generated by Django 2.2.16 on 2020-11-27 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_3ingredients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='cooking_time',
            field=models.TextField(),
        ),
    ]
