# Generated by Django 2.2.16 on 2020-11-27 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_3ingredients', '0002_auto_20201127_0430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='cooking_time',
            field=models.IntegerField(),
        ),
    ]
