# Generated by Django 2.2.16 on 2020-11-29 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_3ingredients', '0003_auto_20201127_0457'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipes',
            old_name='group',
            new_name='category',
        ),
    ]
