# Generated by Django 2.2.16 on 2020-12-02 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_3ingredients', '0004_auto_20201129_0541'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recipes',
            new_name='Recipe',
        ),
    ]
